"use client";

import { useEffect, useState } from "react";

export type SiteLanguage = "hi" | "en";
const STORAGE_KEY = "panditji-language";
const words: Record<string, string> = {
  "होम": "Home",
  "पंडित जी के बारे में": "About the Pandit",
  "कुंडली विश्लेषण": "Kundali Analysis",
  "ऑनलाइन पूजा बुकिंग": "Online Puja Booking",
  "दोष विश्लेषक": "Dosha Analyzer",
  "पूजा मुहूर्त": "Puja Muhurat",
  "संपर्क करें": "Contact",
  "परामर्श बुक करें": "Book a Consultation",
  "काल सर्प दोष पूजा": "Kaal Sarp Dosha Puja",
  "मंगल दोष पूजा": "Mangal Dosha Puja",
  "अंगारक दोष पूजा": "Angarak Dosha Puja",
  "गुरु चांडाल दोष पूजा": "Guru Chandal Dosha Puja",
  "ग्रहण दोष पूजा": "Grahan Dosha Puja",
  "नवग्रह शांति पूजा": "Navgraha Shanti Puja",
  "महामृत्युंजय जाप": "Mahamrityunjaya Jaap",
  "रुद्राभिषेक": "Rudrabhishek",
  "पितृ दोष पूजा": "Pitri Dosha Puja",
  "वैदिक वास्तु शांति": "Vedic Vastu Shanti",
  "सभी पूजा सेवाएँ देखें": "Explore all puja services",
  "पूजा सेवाएँ": "Puja Services",
  "विशेष वैदिक अनुष्ठान": "Featured Vedic rituals",
  "अधिक": "More",
  "अधिक नेविगेशन विकल्प": "More navigation options",
  "अन्य विकल्प": "Other options",
  "मेरा अकाउंट": "My account",
  "लॉगआउट": "Log out",
  "लॉगिन": "Log in",
  "साइन अप": "Sign up",
  "बुकिंग": "Bookings",
  "कुंडली": "Kundali",
  "मेनू": "Menu",
  "पूजा सेवाएँ बंद करें": "Close puja services",
  "मेनू बंद करें": "Close menu",
  "हीरो संदेश चुनें": "Choose a featured message",
  "शुभ मुहूर्त के अनुसार": "According to auspicious timings",
  "वैदिक ज्योतिष से अपने जीवन को समझें।": "Understand your life through Vedic astrology.",
  "जन्म कुंडली, ग्रहों और जीवन की परिस्थितियों को समझकर व्यक्तिगत मार्गदर्शन प्राप्त करें।": "Receive personal guidance through your birth chart, planetary positions, and life circumstances.",
  "पूजा बुक करें": "Book a puja",
  "ज्योतिष परामर्श": "Astrology consultation",
  "उज्जैन से वैदिक सेवाएँ": "Vedic services from Ujjain",
  "महाकाल की नगरी से श्रद्धा और शांति की ओर बढ़ें।": "Find devotion and peace in the city of Mahakal.",
  "उज्जैन की पावन भूमि से पारंपरिक पूजा, अनुष्ठान और ज्योतिषीय परामर्श प्राप्त करें।": "Access traditional pujas, rituals, and astrology consultations from sacred Ujjain.",
  "पारंपरिक विधि-विधान के साथ": "With traditional rituals",
  "महाकाल की भक्ति से जीवन में नई ऊर्जा पाएँ।": "Find renewed energy through devotion to Mahakal.",
  "व्यक्तिगत ज्योतिषीय मार्गदर्शन": "Personal astrology guidance",
  "ग्रहों को समझें, अपने जीवन को नई दृष्टि से देखें।": "Understand the planets and see your life from a new perspective.",
  "हमारे बारे में": "About us",
  "पंडित सुमित शर्मा जी": "Pandit Sumit Sharma Ji",
  "वैदिक ज्योतिष": "Vedic astrology",
  "पूजा अनुष्ठान": "Puja rituals",
  "दोष निवारण": "Traditional dosha guidance",
  "महाकाल की नगरी उज्जैन से वैदिक ज्योतिष, पूजा अनुष्ठान और पारंपरिक धार्मिक मार्गदर्शन की सेवाएँ। प्रत्येक पूजा और ज्योतिषीय परामर्श में व्यक्ति की परिस्थिति, उद्देश्य और आवश्यकताओं को समझने पर ध्यान दिया जाता है।": "Vedic astrology, puja rituals, and traditional spiritual guidance from Ujjain, the city of Mahakal. Every puja and consultation begins by understanding each person's circumstances, intentions, and needs.",
  "परंपरा के साथ मार्गदर्शन, आस्था के साथ सम्मान।": "Guidance rooted in tradition, with respect for your faith.",
  "पंडित जी के बारे में जानें": "Learn about the Pandit",
  "उज्जैन, मध्य प्रदेश": "Ujjain, Madhya Pradesh",
  "स्थान": "Location",
  "फोन": "Phone",
  "ईमेल": "Email",
  "Instagram": "Instagram",
  "संपर्क": "Contact",
  "त्वरित लिंक": "Quick links",
  "पूजा सेवाएँ देखें": "Explore puja services",
  "पंडित सुमित शर्मा जी की वैदिक सेवाएँ": "Vedic services by Pandit Sumit Sharma Ji",
  "नाम": "Name",
  "पूरा नाम": "Full name",
  "जन्म तारीख": "Birth date",
  "जन्म समय": "Birth time",
  "जन्म स्थान": "Birthplace",
  "लिंग": "Gender",
  "वैकल्पिक": "Optional",
  "न बताना चाहें": "Prefer not to say",
  "अपना नाम लिखें": "Enter your name",
  "अपनी जानकारी भरें": "Enter your details",
  "जमा करें": "Submit",
  "भेजें": "Send",
  "बुक करें": "Book",
  "बुकिंग विवरण": "Booking details",
  "ग्राहक की जानकारी": "Customer information",
  "पूजा की जानकारी": "Puja information",
  "जन्म संबंधी जानकारी": "Birth details",
  "मोबाइल नंबर": "Mobile number",
  "शहर / स्थान": "City / place",
  "पूजा": "Puja",
  "पसंदीदा तिथि": "Preferred date",
  "पसंदीदा समय": "Preferred time",
  "पूजा का स्थान": "Puja location",
  "उद्देश्य": "Purpose",
  "अतिरिक्त जानकारी": "Additional information",
  "अपना संदेश लिखें": "Write your message",
  "आपका नाम": "Your name",
  "आपका ईमेल": "Your email",
  "आपका फोन": "Your phone",
  "संदेश": "Message",
  "संदेश भेजें": "Send message",
  "धन्यवाद": "Thank you",
  "बंद करें": "Close",
  "वापस जाएँ": "Go back",
  "नई कुंडली": "New chart",
  "लग्न": "Ascendant",
  "चंद्र राशि": "Moon sign",
  "सूर्य राशि": "Sun sign",
  "समग्र दृष्टि": "Overview",
  "ग्रह स्थिति": "Planet positions",
  "ग्रह": "Planet",
  "राशि": "Sign",
  "भाव": "House",
  "नक्षत्र": "Nakshatra",
  "अंश": "Degree",
  "स्थिति": "Motion",
  "वक्री": "Retrograde",
  "सीधी": "Direct",
  "गणना": "Calculation",
  "पारंपरिक योग / दोष संकेत": "Traditional yoga / dosha indicators",
  "अपनी कुंडली के बारे में और पूछें": "Ask more about your birth chart",
  "पूछें": "Ask",
  "उत्तर तैयार हो रहा है…": "Preparing an answer…",
  "आपकी कुंडली": "Your birth chart",
  "करियर एवं नौकरी": "Career & work",
  "विवाह": "Marriage",
  "प्रेम एवं संबंध": "Love & relationships",
  "वित्त": "Finance",
  "शिक्षा": "Education",
  "परिवार": "Family",
  "यात्रा एवं विदेश": "Travel & abroad",
  "आध्यात्मिकता": "Spirituality",
  "मार्गदर्शन": "Guidance",
  "विश्लेषण": "Reading",
  "समय": "Timing",
  "विवाह का स्वरूप": "Marriage style",
  "उपलब्ध नहीं": "Unavailable",
  "यह पारंपरिक ज्योतिषीय व्याख्या है, निश्चित भविष्यवाणी नहीं।": "This is a traditional astrological interpretation, not a definite prediction.",
  "तिथि": "Date",
  "वार": "Weekday",
  "योग": "Yoga",
  "करण": "Karana",
  "सूर्योदय": "Sunrise",
  "सूर्यास्त": "Sunset",
  "चंद्रोदय": "Moonrise",
  "चंद्रास्त": "Moonset",
  "आज": "Today",
  "मास": "Month",
  "वर्ष": "Year",
  "अगला": "Next",
  "पिछला": "Previous",
  "साझा करें": "Share",
  "डाउनलोड": "Download",
  "लोड हो रहा है…": "Loading…",
  "जानकारी उपलब्ध नहीं है।": "Information is unavailable.",
  "कृपया कुछ समय बाद पुनः प्रयास करें।": "Please try again in a little while.",
  "सभी सेवाएँ देखें": "View all services",
  "अधिक जानें": "Learn more",
  "अभी बुक करें": "Book now",
  "विवरण देखें": "View details",
  "विशेषताएँ": "Highlights",
  "अक्सर पूछे जाने वाले प्रश्न": "Frequently asked questions",
  "सामान्य प्रश्न": "Common questions",
  "पूजा की प्रक्रिया": "Puja process",
  "पूजा का उद्देश्य": "Purpose of the puja",
  "यह सेवा किसके लिए है": "Who this service is for",
  "बुकिंग के लिए आवश्यक जानकारी": "Information needed for booking",
  "संबंधित सेवाएँ": "Related services",
  "क्या आप परामर्श चाहते हैं?": "Would you like a consultation?",
  "अपनी सेवा चुनें": "Choose a service",
  "अपनी सुविधा के अनुसार तिथि चुनें": "Choose a convenient date",
  "ऑनलाइन": "Online",
  "उज्जैन में": "In Ujjain",
  "अन्य स्थान": "Other location",
  "सुबह": "Morning",
  "दोपहर": "Afternoon",
  "शाम": "Evening",
  "चर्चा करके तय करें": "Decide after discussion",
  "हमसे जुड़ें": "Connect with us",
  "हमें संदेश भेजें": "Send us a message",
  "हमसे संपर्क करने के लिए धन्यवाद।": "Thank you for contacting us.",
  "अपनी पूजा बुकिंग का अनुरोध भेजें": "Send a puja booking request",
  "पूजा बुकिंग अनुरोध भेजें": "Send puja booking request",
  "बुकिंग अनुरोध": "Booking request",
  "उपलब्धता की पुष्टि संपर्क के बाद की जाएगी।": "Availability will be confirmed after we contact you.",
  "कृपया सही जानकारी दर्ज करें।": "Please enter valid information.",
  "कृपया अपना नाम दर्ज करें।": "Please enter your name.",
  "कृपया अपना मोबाइल नंबर दर्ज करें।": "Please enter your mobile number.",
  "कृपया पूजा का उद्देश्य चुनें।": "Please choose the purpose of the puja.",
  "कृपया पूजा की तिथि चुनें।": "Please choose a puja date.",
  "कृपया पूजा का स्थान चुनें।": "Please choose a puja location.",
  "मैंने गोपनीयता नीति पढ़ ली है।": "I have read the privacy policy.",
  "आपकी जानकारी सुरक्षित रखी जाएगी।": "Your information will be kept secure.",
  "आवश्यक जानकारी": "Information required",
  "वैकल्पिक जानकारी": "Optional information",
  "नियम एवं शर्तें": "Terms and conditions",
  "गोपनीयता नीति": "Privacy policy",
  "वापस होम पर जाएँ": "Return home",
  "मुख्य पृष्ठ": "Home page",
  "यहाँ क्लिक करें": "Click here",
  "कृपया प्रतीक्षा करें…": "Please wait…",
  "बुकिंग भेजी जा रही है…": "Sending your booking…",
  "आपकी बुकिंग का अनुरोध प्राप्त हो गया है।": "Your booking request has been received.",
  "हम शीघ्र आपसे संपर्क करेंगे।": "We will contact you soon.",
  "पूजा के बारे में": "About the puja",
  "पूजा क्यों की जाती है?": "Why is this puja performed?",
  "पूजा के उद्देश्य": "Purpose of the puja",
  "पूजा में शामिल गतिविधियाँ": "Activities included in the puja",
  "यह पूजा किसके लिए हो सकती है?": "Who may consider this puja?",
  "बुकिंग एवं उपलब्धता": "Booking & availability",
  "उज्जैन से पूजा अनुरोध भेजें": "Request a puja from Ujjain",
  "अपनी पसंदीदा तिथि, स्थान और आवश्यकता साझा करें। पूजा की उपलब्धता तथा उचित प्रक्रिया की पुष्टि संपर्क के बाद की जाएगी।": "Share your preferred date, location, and requirements. Puja availability and arrangements will be confirmed after we contact you.",
  "परंपरा और संदर्भ": "Tradition & context",
  "संकल्प के अनुसार": "According to your intention",
  "पारंपरिक विधि": "Traditional process",
  "पारंपरिक विधि-विधान": "Traditional rituals",
  "अन्य सेवाएँ": "Other services",
  "संबंधित पूजा सेवाएँ": "Related puja services",
  "ब्रेडक्रंब": "Breadcrumb",
  "क्या पूजा की तिथि तुरंत निश्चित हो जाती है?": "Is the puja date confirmed immediately?",
  "नहीं। पसंदीदा तिथि एक अनुरोध है; उपलब्धता और व्यवस्था की पुष्टि संपर्क के बाद की जाती है।": "No. Your preferred date is a request; availability and arrangements are confirmed after contact.",
  "पूजा के लिए कौन-सी जानकारी उपयोगी होती है?": "What information is useful for the puja?",
  "नाम, संपर्क विवरण, पूजा का उद्देश्य, पसंदीदा तिथि और स्थान उपयोगी होते हैं। जन्म विवरण केवल आवश्यक होने पर साझा किए जा सकते हैं।": "Your name, contact details, purpose, preferred date, and location are useful. Birth details need only be shared when required.",
  "क्या पूजा ऑनलाइन भी हो सकती है?": "Can the puja also be conducted online?",
  "कुछ सेवाओं के लिए ऑनलाइन मार्गदर्शन या चर्चा संभव हो सकती है। उपयुक्त माध्यम के लिए पहले संपर्क करें।": "Online guidance or discussion may be possible for some services. Contact us first to confirm a suitable option.",
  "क्या परिणाम की गारंटी दी जाती है?": "Are results guaranteed?",
  "नहीं। यह धार्मिक और पारंपरिक अनुष्ठान है। अनुभव व्यक्तिगत आस्था, परिस्थिति और परंपरा के अनुसार भिन्न हो सकता है।": "No. This is a religious and traditional ritual. Experiences may vary according to personal faith, circumstances, and tradition.",
  "पूजा सामग्री कौन उपलब्ध कराता है?": "Who provides the puja materials?",
  "सामग्री और व्यवस्था पूजा के प्रकार, स्थान और परंपरा के अनुसार बताई जाती है। बुकिंग अनुरोध के बाद आवश्यक जानकारी साझा की जाएगी।": "Materials and arrangements depend on the puja, location, and tradition. Details will be shared after your booking request.",
  "क्या अपेक्षा रखें": "What to expect",
  "जन्मकुंडली": "birth chart",
  "पंडित जी से परामर्श लें": "Consult the Pandit",
  "व्यक्तिगत परामर्श": "Personal consultation",
  "आभार": "Thank you",
  "अगला पृष्ठ": "Next page",
  "पिछला पृष्ठ": "Previous page",
  "जारी रखें": "Continue",
  "रद्द करें": "Cancel",
  "सहेजें": "Save",
  "हटाएँ": "Delete",
  "खोजें": "Search",
  "स्थान बदलें": "Change location",
  "स्थान लागू करें": "Apply location",
  "शहर": "City",
  "राज्य": "State",
  "देश": "Country",
  "अक्षांश": "Latitude",
  "देशांतर": "Longitude",
  "टाइमज़ोन": "Time zone",
  "कृपया स्थान और सही अक्षांश-देशांतर भरें।": "Enter a location and valid latitude and longitude.",
  "उज्जैन चुनें": "Select Ujjain",
  "महीना": "Month",
  "पूरा कैलेंडर": "Full calendar",
  "त्योहार": "Festivals",
  "व्रत": "Fasts",
  "शुभ समय": "Auspicious times",
  "अशुभ समय": "Inauspicious times",
  "राहु काल": "Rahu Kaal",
  "अभिजीत मुहूर्त": "Abhijit Muhurat",
  "यमगण्ड": "Yamaganda",
  "गुलिक काल": "Gulika Kaal",
  "दिन": "Day",
  "रात": "Night",
  "सुबह का समय": "Morning",
  "अभी उपलब्ध नहीं": "Not available right now"
};
const serviceWords: Record<string, string> = {
  "कालसर्प दोष पूजा": "Kaal Sarp Dosha Puja", "काल सर्प दोष पूजा": "Kaal Sarp Dosha Puja", "उज्जैन में पारंपरिक विधि द्वारा कालसर्प दोष शांति अनुष्ठान": "Traditional Kaal Sarp Dosha peace ritual in Ujjain", "कालसर्प दोष पूजा एक पारंपरिक ज्योतिषीय एवं धार्मिक अनुष्ठान है, जिसे जन्मकुंडली में बताए गए कालसर्प योग से संबंधित मान्यताओं के संदर्भ में समझा जाता है।": "Kaal Sarp Dosha Puja is a traditional astrological and religious ritual associated with beliefs about Kaal Sarp Yoga in a birth chart.", "पारंपरिक ज्योतिषीय विचार में राहु और केतु की स्थिति के संदर्भ में इस योग का अध्ययन किया जाता है। भगवान शिव की आराधना, मंत्र जाप और शांति अनुष्ठान आस्था-आधारित परंपराओं का हिस्सा हो सकते हैं।": "In traditional astrology, this yoga is considered in relation to Rahu and Ketu. Devotion to Lord Shiva, mantra recitation, and peace rituals may form part of faith-based traditions.", "यह जानकारी उन लोगों के लिए उपयोगी हो सकती है जो अपनी जन्मकुंडली में कालसर्प योग से जुड़े प्रश्नों और पारंपरिक अनुष्ठानों के बारे में जानना चाहते हैं।": "For people seeking to understand traditional rituals and questions related to Kaal Sarp Yoga in their birth chart.",
  "मंगल दोष पूजा": "Mangal Dosha Puja", "मंगल ग्रह से संबंधित पारंपरिक शांति अनुष्ठान एवं ज्योतिषीय मार्गदर्शन": "Traditional peace ritual and astrological guidance related to Mars", "मंगल दोष पूजा मंगल ग्रह से संबंधित पारंपरिक ज्योतिषीय मान्यताओं और धार्मिक शांति अनुष्ठानों के संदर्भ में की जाने वाली पूजा है।": "Mangal Dosha Puja is performed in the context of traditional astrological beliefs about Mars and religious peace rituals.", "जन्मकुंडली में मंगल की स्थिति को पारंपरिक ज्योतिषीय दृष्टि से देखा जाता है। यह किसी परिस्थिति का निश्चित कारण नहीं बताती; व्यक्तिगत कुंडली और संदर्भ के अनुसार मार्गदर्शन लिया जा सकता है।": "Mars in a birth chart is considered through traditional astrology. It does not establish a definite cause for life circumstances; guidance depends on the individual chart and context.", "यह सेवा उन लोगों के लिए है जो मंगल की स्थिति, विवाह से जुड़े ज्योतिषीय प्रश्नों या पारंपरिक मंगल शांति अनुष्ठान के बारे में जानकारी चाहते हैं।": "For people seeking information about Mars placements, astrology questions related to marriage, or traditional Mangal peace rituals.",
  "अंगारक दोष पूजा": "Angarak Dosha Puja", "अंगारक दोष से संबंधित पारंपरिक ज्योतिषीय मार्गदर्शन एवं शांति अनुष्ठान": "Traditional astrological guidance and peace ritual related to Angarak Dosha", "अंगारक दोष पूजा मंगल और राहु से संबंधित पारंपरिक ज्योतिषीय अवधारणाओं के संदर्भ में जानकारी और धार्मिक शांति अनुष्ठान के लिए की जाती है।": "Angarak Dosha Puja offers information and a religious peace ritual in the context of traditional astrological concepts related to Mars and Rahu.", "पारंपरिक ज्योतिष में मंगल और राहु की स्थिति को अलग-अलग संदर्भों में पढ़ा जाता है। इसे स्थापित वैज्ञानिक तथ्य के बजाय आस्था और परंपरा के संदर्भ में समझना उचित है।": "Traditional astrology interprets Mars and Rahu in context. These beliefs are best understood as matters of faith and tradition, not established scientific facts.", "यह उन लोगों के लिए उपयुक्त हो सकती है जो अंगारक योग से जुड़ी पारंपरिक व्याख्याओं और धार्मिक अनुष्ठान के बारे में जानकारी चाहते हैं।": "For people seeking information about traditional interpretations and rituals associated with Angarak Yoga.",
  "गुरु चांडाल दोष पूजा": "Guru Chandal Dosha Puja", "गुरु चांडाल दोष से संबंधित पारंपरिक ज्योतिषीय अध्ययन एवं अनुष्ठान": "Traditional astrological study and ritual related to Guru Chandal Dosha", "गुरु चांडाल दोष पूजा गुरु और राहु या केतु से संबंधित पारंपरिक ज्योतिषीय विचारों के संदर्भ में समझी जाने वाली धार्मिक शांति पूजा है।": "Guru Chandal Dosha Puja is a religious peace ritual understood through traditional astrological ideas related to Jupiter and Rahu or Ketu.", "जन्मकुंडली में ग्रहों की स्थिति का पारंपरिक अध्ययन व्यक्ति विशेष के संदर्भ में किया जाता है। इसे निश्चित भविष्यवाणी या गारंटी के रूप में प्रस्तुत नहीं किया जाता।": "Planetary placements are traditionally studied in the context of each person's birth chart, not as definite predictions or guarantees.", "ऐसे लोग जो गुरु चांडाल योग से जुड़े पारंपरिक प्रश्नों के बारे में विनम्र और सूचनात्मक मार्गदर्शन चाहते हैं।": "For people seeking respectful, informative guidance about traditional questions related to Guru Chandal Yoga.",
  "ग्रहण दोष पूजा": "Grahan Dosha Puja", "ग्रहण दोष से संबंधित पारंपरिक ज्योतिषीय मान्यताओं एवं शांति अनुष्ठान": "Traditional astrological beliefs and peace ritual related to Grahan Dosha", "ग्रहण दोष पूजा जन्मकुंडली और ग्रहण से संबंधित पारंपरिक ज्योतिषीय मान्यताओं के संदर्भ में समझी जाने वाली शांति पूजा है।": "Grahan Dosha Puja is a peace ritual understood in the context of traditional astrological beliefs about birth charts and eclipses.", "ग्रहण और ग्रहों के प्रभाव की व्याख्या विभिन्न ज्योतिषीय परंपराओं में मिलती है। पूजा का स्वरूप आस्था, परंपरा और व्यक्तिगत आवश्यकता के अनुसार तय किया जाता है।": "Astrological traditions interpret eclipses and planetary influences in different ways. The puja is shaped by faith, tradition, and individual needs.", "यह उन लोगों के लिए है जो ग्रहण दोष से संबंधित पारंपरिक मान्यताओं और धार्मिक शांति प्रक्रिया के बारे में जानकारी चाहते हैं।": "For people seeking information about traditional beliefs and religious peace rituals related to Grahan Dosha.",
  "पितृ दोष पूजा": "Pitri Dosha Puja", "पितृ संबंधी धार्मिक परंपराओं एवं शांति अनुष्ठान के लिए मार्गदर्शन": "Guidance on ancestral traditions and peace rituals", "पितृ दोष पूजा पितृ स्मरण, तर्पण और श्राद्ध जैसी भारतीय धार्मिक परंपराओं के सांस्कृतिक व आध्यात्मिक संदर्भ में जानकारी और मार्गदर्शन देती है।": "Pitri Dosha Puja offers guidance in the cultural and spiritual context of Indian traditions such as remembering ancestors, Tarpan, and Shraddha.", "पितृ संबंधी अनुष्ठान श्रद्धा, स्मरण और पारिवारिक परंपरा से जुड़े हैं। इनके बारे में भय या अपराधबोध पैदा करने के बजाय सम्मानजनक और व्यक्तिगत परिस्थिति के अनुरूप जानकारी ली जानी चाहिए।": "Ancestral rituals are connected with devotion, remembrance, and family tradition. Information should be shared respectfully, without creating fear or guilt.", "यह सेवा उन परिवारों के लिए उपयोगी हो सकती है जो पितृ स्मरण से जुड़े धार्मिक रीति-रिवाजों के बारे में संवेदनशील और सम्मानजनक मार्गदर्शन चाहते हैं।": "For families seeking sensitive, respectful guidance about religious customs related to honoring ancestors.",
  "नवग्रह शांति पूजा": "Navgraha Shanti Puja", "नवग्रहों से संबंधित वैदिक पूजा एवं पारंपरिक शांति अनुष्ठान": "Vedic worship and traditional peace ritual for the nine planets", "नवग्रह शांति पूजा सूर्य, चंद्रमा, मंगल, बुध, गुरु, शुक्र, शनि, राहु और केतु से जुड़ी वैदिक पूजा एवं पारंपरिक शांति अनुष्ठान है।": "Navgraha Shanti Puja is a Vedic worship and traditional peace ritual connected with the Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.", "नवग्रहों का उल्लेख भारतीय धार्मिक और ज्योतिषीय परंपराओं में मिलता है। व्यक्तिगत कुंडली या संकल्प के अनुसार पूजा की विधि और सामग्री अलग हो सकती है।": "The nine planets appear in Indian religious and astrological traditions. Ritual methods and materials may vary according to a person's chart or intention.", "यह उन लोगों के लिए है जो नवग्रह पूजा की परंपरा, मंत्र जाप या व्यक्तिगत ज्योतिषीय प्रश्नों के संदर्भ में जानकारी चाहते हैं।": "For people seeking information about Navgraha worship, mantra recitation, or personal astrological questions.",
  "महामृत्युंजय मंत्र जाप": "Mahamrityunjaya Mantra Recitation", "भगवान शिव की आराधना एवं पारंपरिक मंत्र अनुष्ठान": "Devotion to Lord Shiva and a traditional mantra ritual", "महामृत्युंजय मंत्र जाप भगवान शिव की आराधना से जुड़ा पारंपरिक धार्मिक और आध्यात्मिक अनुष्ठान है, जिसमें संकल्प के अनुसार मंत्र जाप किया जाता है।": "Mahamrityunjaya mantra recitation is a traditional religious and spiritual ritual devoted to Lord Shiva, performed according to one's intention.", "यह मंत्र शैव परंपरा में विशेष महत्व रखता है। जाप की अवधि, संख्या और विधि परंपरा तथा व्यक्तिगत संकल्प के अनुसार तय होती है। यह चिकित्सा उपचार का विकल्प या स्वास्थ्य की गारंटी नहीं है।": "This mantra holds special significance in Shaivite tradition. Its duration and method follow tradition and personal intention. It is not a substitute for medical treatment or a health guarantee.", "यह सेवा उन श्रद्धालुओं के लिए है जो भगवान शिव की आराधना और पारंपरिक मंत्र जाप अनुष्ठान के बारे में जानकारी चाहते हैं।": "For devotees seeking information about worship of Lord Shiva and traditional mantra recitation.",
  "रुद्राभिषेक": "Rudrabhishek", "भगवान शिव की विशेष पूजा एवं पारंपरिक अभिषेक अनुष्ठान": "Special worship of Lord Shiva and a traditional Abhishek ritual", "रुद्राभिषेक भगवान शिव की आराधना से जुड़ा विशेष पारंपरिक अभिषेक अनुष्ठान है। इसमें शिवलिंग का अभिषेक, वैदिक मंत्र जाप, संकल्प और आरती शामिल हो सकते हैं।": "Rudrabhishek is a special traditional ritual devoted to Lord Shiva. It may include bathing the Shiva Lingam, Vedic mantra recitation, a personal intention, and Aarti.", "शैव परंपरा में रुद्राभिषेक श्रद्धा और संकल्प के साथ किया जाता है। पूजा सामग्री, विधि और अवधि स्थान तथा परंपरा के अनुसार भिन्न हो सकती है।": "In Shaivite tradition, Rudrabhishek is performed with devotion and intention. Materials, methods, and duration vary by place and tradition.", "यह उन श्रद्धालुओं के लिए है जो भगवान शिव की पूजा, अभिषेक की प्रक्रिया और पारंपरिक अनुष्ठान के बारे में जानकारी चाहते हैं।": "For devotees seeking information about worship of Lord Shiva, the Abhishek process, and traditional rituals.",
  "वैदिक वास्तु शांति": "Vedic Vastu Shanti", "घर, गृह प्रवेश एवं कार्यस्थल के लिए पारंपरिक वास्तु शांति अनुष्ठान": "A traditional Vastu peace ritual for homes, housewarmings, and workplaces", "वैदिक वास्तु शांति घर, गृह प्रवेश या कार्यस्थल से जुड़े धार्मिक शांति अनुष्ठान और पारंपरिक मार्गदर्शन के लिए की जाने वाली पूजा है।": "Vedic Vastu Shanti is a puja offering traditional guidance and a religious peace ritual for a home, housewarming, or workplace.", "वास्तु से संबंधित मान्यताएँ भारतीय परंपराओं में स्थान रखती हैं। पूजा का उद्देश्य धार्मिक संकल्प और परंपरागत विधि है; इससे वित्त, स्वास्थ्य, संबंध या व्यवसाय के निश्चित परिणाम का दावा नहीं किया जाता।": "Vastu beliefs have a place in Indian traditions. This puja is a religious observance rooted in traditional practice; it does not guarantee financial, health, relationship, or business outcomes.", "यह सेवा नए घर, गृह प्रवेश, कार्यालय या कार्यस्थल के लिए पारंपरिक पूजा एवं धार्मिक मार्गदर्शन चाहने वालों के लिए उपयुक्त हो सकती है।": "For people seeking traditional puja and religious guidance for a new home, housewarming, office, or workplace.",
};
const allWords = { ...words, ...serviceWords };
const englishToHindi = Object.fromEntries(Object.entries(allWords).map(([hindi, english]) => [english, hindi]));
function applyLanguage(language: SiteLanguage) {
  document.documentElement.lang = language;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    const original = node.nodeValue;
    if (!original) continue;
    const trimmed = original.trim();
    const translated = language === "en" ? allWords[trimmed] : englishToHindi[trimmed];
    if (translated) node.nodeValue = original.replace(trimmed, translated);
  }
  const attrMap: Record<string, string> = { placeholder: "placeholder", title: "title", "aria-label": "aria-label" };
  document.querySelectorAll<HTMLElement>("[placeholder], [title], [aria-label]").forEach((element) => {
    for (const attribute of Object.keys(attrMap)) {
      const value = element.getAttribute(attribute);
      const translated = value ? (language === "en" ? allWords[value] : englishToHindi[value]) : undefined;
      if (translated) element.setAttribute(attribute, translated);
    }
  });
}

export function getSavedLanguage(): SiteLanguage { return typeof window !== "undefined" && localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "hi"; }
export function setSiteLanguage(language: SiteLanguage) {
  localStorage.setItem(STORAGE_KEY, language);
  applyLanguage(language);
  window.dispatchEvent(new CustomEvent("panditji-language-change", { detail: language }));
}

export default function SiteLanguageControl() {
  const [language, setLanguage] = useState<SiteLanguage>("hi");
  const [ready, setReady] = useState(false);
  const [showPrompt, setShowPrompt] = useState(false);
  useEffect(() => {
    const initialize = window.setTimeout(() => {
      const saved = localStorage.getItem(STORAGE_KEY);
      const initial: SiteLanguage = saved === "en" ? "en" : "hi";
      setLanguage(initial); setShowPrompt(!saved); setReady(true); applyLanguage(initial);
    }, 0);
    const observer = new MutationObserver(() => applyLanguage(getSavedLanguage()));
    observer.observe(document.body, { subtree: true, childList: true, characterData: true });
    return () => { window.clearTimeout(initialize); observer.disconnect(); };
  }, []);
  const choose = (value: SiteLanguage) => { setSiteLanguage(value); setLanguage(value); setShowPrompt(false); };
  return <>
    <div className="fixed right-3 top-4 z-[70] rounded-full border border-[#dfc6a4] bg-white p-1 shadow-lg lg:top-[88px]"><button type="button" aria-label="हिन्दी" aria-pressed={language === "hi"} onClick={() => choose("hi")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${language === "hi" ? "bg-[#8b3516] text-white" : "text-[#70401f]"}`}>हिन्दी</button><button type="button" aria-label="English" aria-pressed={language === "en"} onClick={() => choose("en")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${language === "en" ? "bg-[#8b3516] text-white" : "text-[#70401f]"}`}>EN</button></div>
    {ready && showPrompt && <div className="fixed inset-0 z-[100] grid place-items-center bg-[#291307]/65 p-4" role="dialog" aria-modal="true" aria-labelledby="language-title"><section className="w-full max-w-md rounded-3xl border border-[#ead6b9] bg-[#fffdf8] p-7 text-center shadow-2xl"><p className="text-sm font-bold tracking-widest text-[#a45b24]">WELCOME · स्वागत है</p><h2 id="language-title" className="mt-3 text-2xl font-black text-[#51230f]">Choose your language</h2><p className="mt-2 text-[#70401f]">अपनी पसंदीदा भाषा चुनें</p><div className="mt-6 grid grid-cols-2 gap-3"><button type="button" autoFocus onClick={() => choose("hi")} className="min-h-14 rounded-xl bg-[#8b3516] px-4 font-bold text-white">हिन्दी <span className="block text-xs font-medium">Default</span></button><button type="button" onClick={() => choose("en")} className="min-h-14 rounded-xl border border-[#8b3516] px-4 font-bold text-[#70280f]">English <span className="block text-xs font-medium">Continue in English</span></button></div></section></div>}
  </>;
}
